import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html className="bg-[#E4DCE4] text-[#020202]" lang="en">
        <body>{children}</body>
      </html>
    </ViewTransitions>
  );
}
